title: jwnhy's Blog
logo: ./avatar.webp
description: Be Humble, Be Better.
remote_theme: jekyll-theme-ascii
google_analytics: UA-190454037-1
markdown: kramdown
kramdown:
    math_engine: katex

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      mathjax: true

url: "https://jwnhy.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
